# Generated by Django 2.0 on 2019-11-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('nip', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('job_Position', models.CharField(choices=[('Staff', 'Staff'), ('Non Staff', 'Non Staff')], max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(default='2019-11-06', null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
