# Generated by Django 2.0 on 2019-11-22 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('nip', models.CharField(help_text='Nomor Induk Pegawai', max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama Pegawai', max_length=40)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Pilih Jenis Kelamin', max_length=10, null=True)),
                ('date_of_birth', models.DateField(default='2019-11-06', null=True)),
                ('place_of_birth', models.CharField(max_length=255, null=True)),
                ('address', models.TextField(blank=True, help_text='Masukkan Alamat Pegawai', max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.JobPosition'),
        ),
        migrations.AddField(
            model_name='employee',
            name='kota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.Kota'),
        ),
    ]
