# Generated by Django 2.0 on 2019-11-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, help_text='Masukkan Alamat Pegawai', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Pilih Jenis Kelamin', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_Position',
            field=models.CharField(choices=[('Staff', 'Staff'), ('Non Staff', 'Non Staff')], help_text='Jabatan Pegawai', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(help_text='Nama Pegawai', max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nip',
            field=models.CharField(help_text='Nomor Induk Pegawai', max_length=11, primary_key=True, serialize=False),
        ),
    ]
