# Generated by Django 2.0 on 2019-11-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20191107_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='place_of_birth',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
